Repository KazanExpress/vue-simple-suggest, pull requests merged in 2018-03, with the labels that each got.

#17 Fix #16
  README.md
  docs/index.html
  docs/main.js
  example/src/App.vue
  example/src/README.html
  lib/vue-simple-suggest.vue
  package.json
Labels: bug, refactoring

#18 Implemented #15
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .npmignore
  README.md
  docs/index.html
  docs/main.js
  example/src/README.html
  package-lock.json
  package.json
Labels: enhancement

#21 Dev
  docs/main.js
  lib/vue-simple-suggest.vue
  package-lock.json
  package.json
Labels: bug, enhancement, refactoring

#22 1.3.0
  docs/main.js
  example/src/App.vue
  lib/vue-simple-suggest.vue
  package-lock.json
  package.json
Labels: bug, enhancement, refactoring

#23 V model mode
  README.md
  docs/index.html
  docs/main.js
  example/src/App.vue
  example/src/README.html
  lib/misc.js
  lib/vue-simple-suggest.vue
Labels: enhancement

#24 v1.4.0
  README.md
  docs/index.html
  docs/main.js
  example/src/App.vue
  example/src/README.html
  lib/misc.js
  lib/vue-simple-suggest.vue
  package-lock.json
  package.json
Labels: enhancement
