Repository KazanExpress/vue-simple-suggest, pull requests merged in 2019-10, with the labels that each got.

#165 fix prevent submit
  lib/misc.js
  lib/vue-simple-suggest.vue
Labels: good first issue, hacktoberfest, next release, patch

#175 add showList control
  README.md
  example/src/App.vue
  lib/misc.js
  lib/vue-simple-suggest.vue
Labels: next release

#176 update Enter behavior
  README.md
  example/src/App.vue
  lib/vue-simple-suggest.vue
Labels: minor, next release

#180 Fix readme readability and deprecations
  README.md
  lib/vue-simple-suggest.vue
Labels: minor, next release

#182 Research function run condition
  lib/vue-simple-suggest.vue
Labels: good first issue, next release
