Repository KazanExpress/vue-simple-suggest, pull requests merged in 2021-05, with the labels that each got.

#432 Async custom input component support
  lib/vue-simple-suggest.vue
Labels: patch

#439 Add prop to prevent hide
  lib/vue-simple-suggest.vue
Labels: enhancement, minor, next release

#399 Updated spelling of "miscellaneous"
  README.md
Labels: next release

#442 Fix graphical glitch when using async data retrieval and debouncing
  dist/cjs.js
  dist/es6.js
  dist/es7.js
  dist/iife.js
  dist/umd.js
  lib/vue-simple-suggest.vue
Labels: next release
